# Generated by Django 6.1.1 on 2026-09-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('c', 'Customer'), ('a', 'Admin'), ('s', 'Staff'), ('t', 'Technician')], default='c', max_length=1),
        ),
    ]
