# Generated by Django 6.1 on 2026-08-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['country_code'], name='api_locatio_country_ae8190_idx'),
        ),
    ]
