# Generated by Django 6.1 on 2026-08-23 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_location_country_code_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='location',
            name='api_locatio_user_id_8e898c_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='api_locatio_country_ae8190_idx',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
