# Generated by Django 6.1 on 2026-08-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('c', 'Custumer'), ('t', 'Technician'), ('a', 'Admin')], default='c', max_length=1),
        ),
    ]
