# Generated by Django 6.1.1 on 2026-09-08 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_problemimage_userlocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteStats',
        ),
        migrations.RemoveField(
            model_name='problemimage',
            name='name',
        ),
        migrations.AddField(
            model_name='problemimage',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_images', to='api.booking'),
        ),
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
