# Generated by Django 6.1 on 2026-08-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='api.service'),
        ),
    ]
