# Generated by Django 6.1.1 on 2026-09-08 06:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_sitestats_remove_problemimage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemimage',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[api.models.validate_file_size]),
        ),
    ]
