# Generated by Django 6.1.1 on 2026-09-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_problemimage_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('c', 'confirmed'), ('r', 'rejected')], default='p', max_length=1),
        ),
    ]
