# Generated by Django 6.0.8 on 2026-09-19 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(10)])),
                ('discription', models.TextField(max_length=140, validators=[django.core.validators.MinLengthValidator(60)])),
                ('crouselImage', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='certificate',
            field=models.ImageField(null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nagarita_back',
            field=models.ImageField(null=True, upload_to='nagarita/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nagarita_front',
            field=models.ImageField(null=True, upload_to='nagarita/'),
        ),
    ]
