# Generated by Django 6.0.8 on 2026-09-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_updatehero_alter_profile_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
