# Generated by Django 6.1 on 2026-08-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_technicianrating'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='technicianrating',
            name='unique_rating_per_user_per_technician',
        ),
        migrations.AlterField(
            model_name='technicianrating',
            name='stars',
            field=models.CharField(max_length=5),
        ),
        migrations.RemoveField(
            model_name='technicianrating',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='technicianrating',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='technicianrating',
            name='user',
        ),
    ]
