# Generated by Django 6.0.8 on 2026-09-19 09:32

import api.utils
import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_value', models.CharField(default=api.utils.generate_otp, max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2026, 9, 19, 9, 37, 33, 298653, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
