# Generated by Django 6.1 on 2026-08-26 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_technicianrating_unique_rating_per_user_per_technician_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechnicianRating',
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
