# Generated by Django 6.1 on 2026-08-27 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_technicianrating_profile_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Announcement must be between 10 and 150 characters.', max_length=150, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(150)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
