# Generated by Django 6.0.8 on 2026-09-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_customuser_is_verified_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='serivces/'),
        ),
    ]
