# Generated by Django 6.0.8 on 2026-09-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_kyc_verified',
            field=models.BooleanField(default=False),
        ),
    ]
