# Generated by Django 6.1 on 2026-08-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_totallikesoncomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totallikesoncomment',
            name='likes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
