# Generated by Django 6.0.8 on 2026-10-10 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('technicians', models.ManyToManyField(limit_choices_to={'role': 't'}, related_name='service_areas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
