# Generated by Django 6.0.8 on 2026-10-10 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_servicearea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicearea',
            name='technicians',
        ),
        migrations.CreateModel(
            name='ServiceAreaTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicearea')),
                ('technician', models.ForeignKey(limit_choices_to={'role': 't'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('technician', 'service_area')},
            },
        ),
    ]
