# Generated by Django 6.1 on 2026-08-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_totallikesoncomment_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrouselImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='crousel-images/')),
                ('img2', models.ImageField(upload_to='crousel-images/')),
                ('img3', models.ImageField(upload_to='crousel-images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
